"""0004_add_external_id

Revision ID: 1a2195c4cdd9
Revises: c7bc280107d9
Create Date: 2026-04-15 17:21:41.113722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2195c4cdd9'
down_revision: Union[str, Sequence[str], None] = 'c7bc280107d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_monthly_feedbacks', sa.Column('user_external_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('uq_user_monthly_feedbacks_user_month'), 'user_monthly_feedbacks', type_='unique')
    op.create_unique_constraint('uq_user_monthly_feedbacks_user_month', 'user_monthly_feedbacks', ['user_external_id', 'month'])
    op.create_foreign_key(None, 'user_monthly_feedbacks', 'users', ['user_external_id'], ['external_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_monthly_feedbacks', type_='foreignkey')
    op.drop_constraint('uq_user_monthly_feedbacks_user_month', 'user_monthly_feedbacks', type_='unique')
    op.create_unique_constraint(op.f('uq_user_monthly_feedbacks_user_month'), 'user_monthly_feedbacks', ['user_id', 'month'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_monthly_feedbacks', 'user_external_id')
    # ### end Alembic commands ###
