"""0002_baseDB

Revision ID: 2f23f2ff8ae1
Revises: d2582b65d008
Create Date: 2026-04-12 21:47:37.889207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f23f2ff8ae1'
down_revision: Union[str, Sequence[str], None] = 'd2582b65d008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('external_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('users_backend_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    op.drop_column('users', 'backend_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('backend_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.create_unique_constraint(op.f('users_backend_id_key'), 'users', ['backend_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'external_id')
    # ### end Alembic commands ###
