"""0003_allTables

Revision ID: da3d57deb7a2
Revises: 2f23f2ff8ae1
Create Date: 2026-04-12 22:04:37.538721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da3d57deb7a2'
down_revision: Union[str, Sequence[str], None] = '2f23f2ff8ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('totems',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('messages',
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edito_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('root_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['root_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_messages_author_id', 'messages', ['author_id'], unique=False)
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_table('user_monthly_feedbacks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('worst_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month', name='uq_user_monthly_feedbacks_user_month')
    )
    op.create_index('ix_user_monthly_feedbacks_user_id', 'user_monthly_feedbacks', ['user_id'], unique=False)
    op.create_table('user_totems',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('totem_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('score_snapshot', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['totem_id'], ['totems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'totem_id', 'month', name='uq_user_totems_user_totem_month')
    )
    op.create_index('ix_user_totems_month', 'user_totems', ['month'], unique=False)
    op.create_index('ix_user_totems_user_id', 'user_totems', ['user_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('clarte_des_idees', sa.Float(), nullable=True),
    sa.Column('exactitude_verifiabilite', sa.Float(), nullable=True),
    sa.Column('pertinence', sa.Float(), nullable=True),
    sa.Column('logique_coherence', sa.Float(), nullable=True),
    sa.Column('absence_de_sophismes', sa.Float(), nullable=True),
    sa.Column('ouverture_d_esprit', sa.Float(), nullable=True),
    sa.Column('volonte_de_comprendre', sa.Float(), nullable=True),
    sa.Column('contribution_utile', sa.Float(), nullable=True),
    sa.Column('respect_collaboration', sa.Float(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('score_total', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', name='uq_evaluations_message_id')
    )
    op.create_index('ix_evaluations_message_id', 'evaluations', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evaluations_message_id', table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index('ix_user_totems_user_id', table_name='user_totems')
    op.drop_index('ix_user_totems_month', table_name='user_totems')
    op.drop_table('user_totems')
    op.drop_index('ix_user_monthly_feedbacks_user_id', table_name='user_monthly_feedbacks')
    op.drop_table('user_monthly_feedbacks')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_index('ix_messages_author_id', table_name='messages')
    op.drop_table('messages')
    op.drop_table('totems')
    # ### end Alembic commands ###
